"""Initial migration

Revision ID: 4fd106201b07
Revises: 
Create Date: 2026-05-31 04:26:08.192884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd106201b07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('api_secret', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_accounts_id'), 'broker_accounts', ['id'], unique=False)
    op.create_table('institutional_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('conviction_score', sa.Float(), nullable=True),
    sa.Column('quarter', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_positions_fund_name'), 'institutional_positions', ['fund_name'], unique=False)
    op.create_index(op.f('ix_institutional_positions_id'), 'institutional_positions', ['id'], unique=False)
    op.create_index(op.f('ix_institutional_positions_ticker'), 'institutional_positions', ['ticker'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metrics_id'), 'performance_metrics', ['id'], unique=False)
    op.create_table('sentiment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_scores_asset'), 'sentiment_scores', ['asset'], unique=False)
    op.create_index(op.f('ix_sentiment_scores_id'), 'sentiment_scores', ['id'], unique=False)
    op.create_table('technical_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('indicator_name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_signals_asset'), 'technical_signals', ['asset'], unique=False)
    op.create_index(op.f('ix_technical_signals_id'), 'technical_signals', ['id'], unique=False)
    op.create_table('trading_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('institutional_conf', sa.Boolean(), nullable=True),
    sa.Column('whale_conf', sa.Boolean(), nullable=True),
    sa.Column('technical_conf', sa.Boolean(), nullable=True),
    sa.Column('sentiment_conf', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_signals_asset'), 'trading_signals', ['asset'], unique=False)
    op.create_index(op.f('ix_trading_signals_id'), 'trading_signals', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('whale_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whale_movements_asset'), 'whale_movements', ['asset'], unique=False)
    op.create_index(op.f('ix_whale_movements_id'), 'whale_movements', ['id'], unique=False)
    op.create_index(op.f('ix_whale_movements_timestamp'), 'whale_movements', ['timestamp'], unique=False)
    op.create_table('executed_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['trading_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executed_trades_asset'), 'executed_trades', ['asset'], unique=False)
    op.create_index(op.f('ix_executed_trades_id'), 'executed_trades', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executed_trades_id'), table_name='executed_trades')
    op.drop_index(op.f('ix_executed_trades_asset'), table_name='executed_trades')
    op.drop_table('executed_trades')
    op.drop_index(op.f('ix_whale_movements_timestamp'), table_name='whale_movements')
    op.drop_index(op.f('ix_whale_movements_id'), table_name='whale_movements')
    op.drop_index(op.f('ix_whale_movements_asset'), table_name='whale_movements')
    op.drop_table('whale_movements')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trading_signals_id'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_asset'), table_name='trading_signals')
    op.drop_table('trading_signals')
    op.drop_index(op.f('ix_technical_signals_id'), table_name='technical_signals')
    op.drop_index(op.f('ix_technical_signals_asset'), table_name='technical_signals')
    op.drop_table('technical_signals')
    op.drop_index(op.f('ix_sentiment_scores_id'), table_name='sentiment_scores')
    op.drop_index(op.f('ix_sentiment_scores_asset'), table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index(op.f('ix_performance_metrics_id'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_institutional_positions_ticker'), table_name='institutional_positions')
    op.drop_index(op.f('ix_institutional_positions_id'), table_name='institutional_positions')
    op.drop_index(op.f('ix_institutional_positions_fund_name'), table_name='institutional_positions')
    op.drop_table('institutional_positions')
    op.drop_index(op.f('ix_broker_accounts_id'), table_name='broker_accounts')
    op.drop_table('broker_accounts')
    # ### end Alembic commands ###
